[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p staticfiles", "python manage.py collectstatic --noinput --verbosity 2"]

[start]
cmd = "python manage.py migrate && gunicorn ai_teacher_backend.wsgi --bind 0.0.0.0:$PORT --log-file -"
